config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  


  root 'home#index'


  get 'posts', to: 'posts#index'
  
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, presence: true, length: {minimum: 5}
    
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def new
        @post = Post.new
    end

    def create
        @post = Post.new(post_params)
        if @post.save
          flash[:success] = "Post successfully created"
          redirect_to @post
        else
          flash[:error] = "Something went wrong"
          render 'new'
        end
    end
    
    def index
        @posts = Post.all
    end

    def edit
        @post = Post.find(params[:id])
    end

    def update
        @post = Post.find(params[:id])
        if @post.update(post_params)
          flash[:success] = "Object was successfully updated"
          redirect_to @post
        else
          flash[:error] = "Something went wrong"
          render 'edit'
        end
    end

    def show
        @post = Post.find(params[:id])
    end

    def destroy
        @post = Post.find(params[:id])
        if @post.destroy
            flash[:success] = 'Object was successfully deleted.'
            redirect_to posts_path
        else
            flash[:error] = 'Something went wrong'
            redirect_to posts_path
        end
    end
    

    private
        def post_params
            params.require(:post).permit(:title, :content)
        end
    
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/index.html.erb
<h1>Hello Avocado!</h1>
<%= link_to 'Avocado posts', posts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Avocado</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item active" aria-current="page"><%= link_to 'Home', home_index_path %></li>
  </ol>
</nav>
  </head>
  
  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: @post, local: true do |form|  %>

    <% if @post.errors.any? %>

        <div id='error_explanation'>

            <h2>
                <%= pluralize(@post.errors.count, 'error') %>
                prohibited this post from being saved:
            
            </h2>
            <ul>
                <% @post.errors.full_messages.each do |msg| %>

                    <li><%= msg %></li>

                <% end %>
            
            
            </ul>
        
        
        </div>

    <% end %>


    <p>
    
        <%= form.label :title %>
        <%= form.text_field :title %>
    </p>

    <p>
    
        <%= form.label :content %>
        <%= form.text_area :content %>
    </p>

    <p>
        <%= form.submit %>
    
    </p>


<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing Avocado Posts</h1>

<%= link_to 'New Post', new_post_path  %>

<table>
    <tr>
        <th>Title</th>
        <th>Content</th>
        <th colspan='3'></th>
    
    </tr>

    <% @posts.each do |post| %>

        <tr>
            <td><%= post.title %></td>
            <td><%= post.content %> </td>
            <td><%= link_to 'Show', post_path(post) %> </td>
            <td><%= link_to 'Edit', edit_post_path(post) %> </td>
            <td><%= link_to 'Delete', post_path(post),
                method: :delete, data: { confirm: 'Are you sure?' } %>  </td>
        
        </tr>
    <% end %>

</table>

<%= link_to 'Back', home_index_path  %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p>
    <strong>Title:</strong>
    <%= @post.title %>
</p>

<p>
    <strong>Content:</strong>
    <%= @post.content %>
</p>

<%= link_to 'Back', posts_path %>